version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: "wordpress_mysql"
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/var/lib/mysql
    restart: always
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_ROOT_PASSWORD: rootpass
    volumes:
        - ./mysql-volume/var/lib/mysql/:/var/lib/mysql
        - ./mysql-volume/etc/mysql/:/etc/mysql
        - ./import_database/:/docker-entrypoint-initdb.d
    ports:
        - 3306:3306
  php_apache:
      build: ./docker/php
      container_name: "wordpress_php"
      restart: always
      volumes:
            - ../site:/var/www/html:consistent
      ports:
        - 80:80
        - 443:443 
      depends_on: 
        - db
      links: 
        - db
      environment:
        DB_HOST: db
        DB_DATABASE: wordpress
        DB_USERNAME: root
        DB_PASSWORD: rootpass
  phpmyadmin:
        image: phpmyadmin
        container_name: "wordpress_phpmyadmin"
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_PMADB=phpmyadmin
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=rootpass
        depends_on:
            - db
            - php
        links:
            - db
  mailhog:
      container_name: "wordpress_mailhog"
      image: mailhog/mailhog
      ports:
          - "1025:1025"
          - "8025:8025"
      depends_on:
          - db
          - php
          - phpmyadmin
      hostname: mailhog.laoengenharia.local
